# Funding links for Qepton
# These links will appear in the "Sponsor" button on GitHub

github: whizbangdevelopers
# ko_fi: whizbangdevelopers
# patreon: whizbangdevelopers
# open_collective: qepton
# custom: ['https://www.buymeacoffee.com/whizbangdevelopers']
