name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      description: Is this a new feature or an enhancement to existing functionality?
      options:
        - New Feature
        - Enhancement (improve existing feature)
        - Integration (connect with another service)
        - UI/UX Improvement
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this solve? Why do you need this feature?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Relevant Platform
      description: Which platform(s) would this feature apply to?
      multiple: true
      options:
        - All Platforms
        - Electron (Desktop)
        - PWA (Web)
        - Mobile (Capacitor)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't already been requested
          required: true
