name: Secret Request
description: Request a new repository secret or PAT from the org owner
title: "[Secret]: "
labels: ["infrastructure", "secret-request", "external"]
assignees:
  - wriver4
body:
  - type: markdown
    attributes:
      value: |
        ## Secret Request

        Only the organization owner (`wriver4`) can create PATs with org-level access.
        Use this template to request a new secret be added to repository settings.

        See [REPO-INFRASTRUCTURE.md](../docs/workflows/REPO-INFRASTRUCTURE.md#repository-secrets) for existing secrets documentation.

  - type: input
    id: secret-name
    attributes:
      label: Secret Name
      description: The name for this secret (SCREAMING_SNAKE_CASE)
      placeholder: "MY_NEW_SECRET"
    validations:
      required: true

  - type: dropdown
    id: secret-type
    attributes:
      label: Secret Type
      description: What kind of secret is this?
      options:
        - Personal Access Token (PAT)
        - API Key
        - Credential/Password
        - Other
    validations:
      required: true

  - type: dropdown
    id: create-account
    attributes:
      label: Create From Account
      description: Which GitHub account should create this PAT?
      options:
        - "wriver4 (org owner) - for repo/project/admin scopes"
        - "whizbangdevelopers-user (service account) - for gist scope only"
        - "N/A - not a GitHub PAT"
    validations:
      required: true

  - type: dropdown
    id: store-repo
    attributes:
      label: Store In Repository
      description: Which repository needs this secret?
      options:
        - "Qepton-Dev (dev)"
        - "Qepton (free)"
        - "Qepton-Premium (prem)"
        - "Qepton-Plugins (plug)"
        - "Organization-level secret"
    validations:
      required: true

  - type: checkboxes
    id: scopes
    attributes:
      label: Required Scopes (for PATs)
      description: Select all scopes needed for this token
      options:
        - label: "`repo` - Full control of private repositories"
        - label: "`gist` - Create and manage gists"
        - label: "`project` - Read/write access to projects"
        - label: "`read:org` - Read organization membership"
        - label: "`workflow` - Update GitHub Action workflows"
        - label: "`admin:repo_hook` - Manage repository webhooks"
        - label: "Other (describe below)"

  - type: input
    id: workflow
    attributes:
      label: Used By Workflow
      description: Which workflow file(s) will use this secret?
      placeholder: "my-workflow.yml"
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Why is this secret needed? What will it enable?
      placeholder: |
        This secret is needed to:
        - Enable automated deployment to...
        - Allow the workflow to access...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Notes
      description: Any other relevant information (expiration preferences, fine-grained vs classic PAT, etc.)
    validations:
      required: false
