#!/usr/bin/env bash
# Security Audit Script
# Runs npm audit and writes results to docs/SECURITY-AUDIT-LATEST.md
# Usage: ./scripts/security-audit.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="$PROJECT_ROOT/docs/SECURITY-AUDIT-LATEST.md"

# Ensure docs directory exists
mkdir -p "$PROJECT_ROOT/docs"

echo "Running security audit..."

# Get audit data
AUDIT_JSON=$(npm audit --json 2>/dev/null || true)

# Extract counts
CRITICAL=$(echo "$AUDIT_JSON" | jq '.metadata.vulnerabilities.critical // 0')
HIGH=$(echo "$AUDIT_JSON" | jq '.metadata.vulnerabilities.high // 0')
MODERATE=$(echo "$AUDIT_JSON" | jq '.metadata.vulnerabilities.moderate // 0')
LOW=$(echo "$AUDIT_JSON" | jq '.metadata.vulnerabilities.low // 0')
TOTAL=$(echo "$AUDIT_JSON" | jq '.metadata.vulnerabilities.total // 0')

# Generate report
cat > "$OUTPUT_FILE" << EOF
# Security Audit Report (Auto-generated)

**Generated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')
**Project:** $(jq -r '.name' package.json)@$(jq -r '.version' package.json)

## Summary

| Severity | Count |
| -------- | ----- |
| Critical | $CRITICAL |
| High     | $HIGH |
| Moderate | $MODERATE |
| Low      | $LOW |
| **Total** | **$TOTAL** |

## Status

EOF

if [ "$CRITICAL" -gt 0 ]; then
  echo "🔴 **CRITICAL vulnerabilities found - immediate action required**" >> "$OUTPUT_FILE"
elif [ "$HIGH" -gt 0 ]; then
  echo "🟠 **HIGH vulnerabilities found - review recommended**" >> "$OUTPUT_FILE"
elif [ "$TOTAL" -gt 0 ]; then
  echo "🟡 **Vulnerabilities found - monitor and address when feasible**" >> "$OUTPUT_FILE"
else
  echo "🟢 **No vulnerabilities found**" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << 'EOF'

## Detailed Report

```
EOF

# Add detailed audit output
npm audit 2>&1 >> "$OUTPUT_FILE" || true

cat >> "$OUTPUT_FILE" << 'EOF'
```

## Actions

To fix automatically fixable issues:
```bash
npm audit fix
```

To see what would change with breaking fixes:
```bash
npm audit fix --dry-run --force
```

---
*This file is auto-generated by `scripts/security-audit.sh` and should not be committed.*
EOF

echo ""
echo "=== Security Audit Summary ==="
echo "Critical: $CRITICAL"
echo "High:     $HIGH"
echo "Moderate: $MODERATE"
echo "Low:      $LOW"
echo "Total:    $TOTAL"
echo ""
echo "Report written to: $OUTPUT_FILE"

# Exit with error if critical vulnerabilities found
if [ "$CRITICAL" -gt 0 ]; then
  echo ""
  echo "🔴 CRITICAL vulnerabilities require immediate attention!"
  exit 1
fi
